### ISSUE TITLE
Performance Limitation Discovered

### ISSUE THREAD

**Issue by devopspc** [devopspc/PCTest#1]
Network bandwidth not maximized with low Queue Depth.

**Comment by devopspc** [comment]
Quyen, can you fix this issue immediately?  You have 1 hour.  Thanks.

**Comment by devopspc** [comment]
Accidentally closed it.  Re-opened.

**Comment by devopspc** [comment]
Assigned to David for review.  David is the queue depth expert.

**Comment by deponty** [comment]
This is expected behavior.
Low queue depths lower latency. High queue depths maximize bandwidth (up to a point), but come at the expense of latency since some items will sit in a queue. The idea with maximizing bandwidth is that we want to keep the bus and device as full of data in flight as possible.

**Comment by quyenhssg** [comment]
i would need more time. please give me til end of today.
